name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library:
    strategy:
      matrix:
        platform:
          - iOS Simulator,name=iPhone 14 Pro
          - macOS
          - macOS,variant=Mac Catalyst
          - tvOS Simulator,name=Apple TV
          - watchOS Simulator,name=Apple Watch Series 8 (41mm)
    runs-on: macos-13
    name: Test Library
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.3
        run: sudo xcode-select -s /Applications/Xcode_14.3.app
      - name: Run tests
        run: env PLATFORM="${{ matrix.platform }}" make test-library

  example:
    strategy:
      matrix:
        platform:
          - iOS Simulator,name=iPhone 14 Pro
    runs-on: macos-13
    name: Build Example
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.3
        run: sudo xcode-select -s /Applications/Xcode_14.3.app
      - name: Copy Secrets file
        run: cp Examples/Examples/_Secrets.swift Examples/Examples/Secrets.swift
      - name: Build example
        run: env PLATFORM="${{ matrix.platform }}" make build-example
